[[events]]
type = "LOAD"
infile = "test_files/antihero.txt"
outfile = "test5.txt"

[[events]]
type = "LOAD"
infile = "test_files/ipanema.txt"
outfile = "test6.txt"

[[events]]
type = "LOAD"
infile = "test_files/summertime.txt"
outfile = "test7.txt"

[[events]]
type = "LOAD"
infile = "test_files/wonderful.txt"
outfile = "test8.txt"


[[events]]
type = "CREATE"
method = "PUT"
uri = "test1.txt"
infile = "test_files/antihero.txt"
block = 1
id = 0

[[events]]
type = "CREATE"
method = "PUT"
uri = "test2.txt"
infile = "test_files/ipanema.txt"
block = 1
id = 1

[[events]]
type = "CREATE"
method = "PUT"
uri = "test3.txt"
infile = "test_files/summertime.txt"
block = 1
id = 2

# Send part of the first three requests
[[events]]
type = "SEND_LINE"
id = 0

[[events]]
type = "SEND_HEADERS"
id = 0

[[events]]
type = "SEND_BODY"
size = 4096
id = 0

[[events]]
type = "SEND_LINE"
id = 1

[[events]]
type = "SEND_HEADERS"
id = 1

[[events]]
type = "SEND_BODY"
size = 4096
id = 1

[[events]]
type = "SEND_LINE"
id = 2

[[events]]
type = "SEND_HEADERS"
id = 2

[[events]]
type = "SEND_BODY"
size = 4096
id = 2

# send last request

[[events]]
type = "CREATE"
method = "PUT"
uri = "test4.txt"
infile = "test_files/wonderful.txt"
block = 1
id = 3

[[events]]
type = "SEND_ALL"
id = 3


# Wait to receive out of ourder
[[events]]
type = "WAIT"
id = 3

[[events]]
type = "SEND_BODY"
id = 0

[[events]]
type = "SEND_BODY"
id = 1

[[events]]
type = "SEND_BODY"
id = 2


[[events]]
type = "WAIT"
id = 0

[[events]]
type = "WAIT"
id = 1

[[events]]
type = "WAIT"
id = 2


[[events]]
type = "CREATE"
method = "GET"
uri = "test5.txt"
block = 1
id = 4

[[events]]
type = "CREATE"
method = "GET"
uri = "test6.txt"
block = 1
id = 5

[[events]]
type = "CREATE"
method = "GET"
uri = "test7.txt"
block = 1
id = 6

# Completely send GET request.
[[events]]
type = "SEND_ALL"
id = 4

# Completely send GET request.
[[events]]
type = "SEND_ALL"
id = 5

# Completely send GET request.
[[events]]
type = "SEND_ALL"
id = 6

# Synchronously receive some of the bodies
[[events]]
type = "RECV_PARTIAL"
size = 4096
id = 4

[[events]]
type = "RECV_PARTIAL"
size = 4096
id = 5

[[events]]
type = "RECV_PARTIAL"
size = 4096
id = 6


[[events]]
type = "CREATE"
method = "GET"
uri = "test8.txt"
block = 1
id = 7


# Completely send GET request.
[[events]]
type = "SEND_ALL"
id = 7

[[events]]
type = "WAIT"
id = 7

[[events]]
type = "WAIT"
id = 4

[[events]]
type = "WAIT"
id = 5

[[events]]
type = "WAIT"
id = 6

[[events]]
type = "UNLOAD"
file = "test5.txt"

[[events]]
type = "UNLOAD"
file = "test6.txt"

[[events]]
type = "UNLOAD"
file = "test7.txt"

[[events]]
type = "UNLOAD"
file = "test8.txt"


[[events]]
type = "UNLOAD"
file = "test1.txt"

[[events]]
type = "UNLOAD"
file = "test2.txt"

[[events]]
type = "UNLOAD"
file = "test3.txt"

[[events]]
type = "UNLOAD"
file = "test4.txt"

